config/routes.rb
Rails.application.routes.draw do

  get 'service', to: 'visitors#service'
  get 'about', to: 'visitors#about'
  get 'demo', to: 'visitors#demo'
  get 'terms', to: 'visitors#terms'
  get 'business', to: 'visitors#business'
  get 'promise', to: 'visitors#promise'
  get 'privacy', to: 'visitors#privacy'
  get 'requirements', to: 'visitors#requirements'
  
  get 'qrcode/show'

  devise_for :users, skip: :registrations
  resources :users do
    get :promote
    get :demote
  end

  resources :companies do
    resources :products, except: :index, shallow: true
  end
  
  resources :products, path: '', except: [:index, :new, :create] do
    resources :instructions, shallow: true
    resources :notifications, shallow: true, except: :show
    get :download_qrcode
  end
  
  #resources :instructions, only: [:show, :edit, :destroy]
  #except: [:new, :index]
  
  resources :instructions, except: [:index, :new, :create] do
    resources :documents, except: :show, shallow: true
		resources :orders, shallow: true
    get :primary
  end
  
  resources :documents, except: :show do
    get :download
  end

  root to: 'visitors#index'
  
  post :search, to: "visitors#search"
  
  post "/about"     => "customers#contact"    , :as => :contact
  post "/callback"  => "customers#callback"   , :as => :callback
  get "customers/close/:id"  => "customers#close"   , :as => :close
  
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  skip_before_filter :authenticate_user!
  
  around_filter :catch_not_found

  
  
  def index
  end
  
  def search
    query = params[:search][:query]
    @product = Product.friendly.find(query.upcase)

    require 'mixpanel-ruby'
    tracker = Mixpanel::Tracker.new(ENV['MIXPANEL_PROJECT_TOKEN'])
    if user_signed_in?
      tracker.track(current_user.id, 'Search', @product.attributes)
    else
      tracker.track(0, 'Search', @product.attributes)
    end

    authorize @product
    redirect_to @product
  end
  
  def service
  end
  
  def about
    @customer = Customer.new
  end

  def promise
  end

  def privacy
  end
  
  private
  
  def catch_not_found
    yield
  rescue ActiveRecord::RecordNotFound
    flash[:alert] = "No product was found for that code. Please ensure the code in the following format: ABC123"
    redirect_to root_path
  end
end

app/views/visitors/_about.html.haml
.box-top
	.lead
		%p dokspot is a cloud application that lets companies manage and distribute their instructions online.
		%p Our current focus allows medical device manufacturers to deliver digital instructions to their customers in a simple and secure manner.

	%br
	.lead Our philosophy

	%h3.dl
		.dt Manufacturer productivity
		%small.dd Simplification is at the core of everything we do.

	%h3.dl
		.dt Customer experience
		%small.dd Our workflow and experience is designed to be straight forward and intuitive.

	%h3.dl
		.dt Team spirit
		%small.dd We do the utmost and work with the best people to provide our customers with the best service.

app/views/visitors/_business.html.haml
.container-fluid.business-top-box.box-top
	.lead dokspot is a cloud platform that lets companies manage and distribute their instructions online - we enable organisations to switch to digital without software development and maintenance headaches.

.container
	.box
		.lead.text-center Features
		.row
			.col-sm-6.col-xs-12
				%h2.glyphicon.glyphicon-cloud.purplecolor.pull-left
				%h3 &nbsp; Robust
				%p.pull-left built and tested for high availability to ensure that your instructions are available when they are required.
			.col-sm-6.col-xs-12
				%h2.glyphicon.glyphicon-ok.purplecolor.pull-left
				%h3 &nbsp; Compliant
				%p.pull-left compliant with Commission Regulation 207/2012 enabling Medical Device Manufacturers to go digital.
		.row
			.col-sm-6.col-xs-12
				%h2.glyphicon.glyphicon-cog.purplecolor.pull-left
				%h3 &nbsp; Controlled
				%p.pull-left upload, release, and archive instructions in a simple and controlled process.
			.col-sm-6.col-xs-12
				%h2.glyphicon.glyphicon-filter.purplecolor.pull-left
				%h3 &nbsp; Simple
				%p.pull-left customers find the right information quickly through the use of dokspot codes.
		.row
			.col-sm-6.col-xs-12
				%h2.glyphicon.glyphicon-comment.purplecolor.pull-left
				%h3 &nbsp; Notifications
				%p.pull-left provide customers with product alerts visible through the dokspot notification service.
			.col-sm-6.col-xs-12
				%h2.glyphicon.glyphicon-map-marker.purplecolor.pull-left
				%h3 &nbsp; Contact Point
				%p.pull-left allow customers to contact manufacturers to discuss product specific questions.
		.row
			.col-sm-6.col-xs-12
				%h2.glyphicon.glyphicon-shopping-cart.purplecolor.pull-left
				%h3 &nbsp; Orders
				%p.pull-left customers can order a paper copy of instructions through the order management service.
			.col-sm-6.col-xs-12
				%h2.glyphicon.glyphicon-font.purplecolor.pull-left
				%h3 &nbsp; Languages
				%p.pull-left help your customers by making instructions available in their preferred language.

app/views/visitors/_promise.html.haml
.box-top
	.lead Equally important to our terms and policies are the promises that we make to our customers.

	%br
	.lead dokspot’s promises to our customers:
	%ul.list-unstyled.lead{style: 'font-size: 16px'}
		%li
			.glyphicon.glyphicon-ok.purplecolor
			&nbsp; You own your content
		%li 
			.glyphicon.glyphicon-ok.purplecolor
			&nbsp; You are in control of what is published and what isn’t
		%li
			.glyphicon.glyphicon-ok.purplecolor
			&nbsp; The platform will continue to innovate and is in constant evolution
		%li 
			.glyphicon.glyphicon-ok.purplecolor
			&nbsp; The service meets the requirements of EU Regulations 207/2012
		%li 
			.glyphicon.glyphicon-ok.purplecolor
			&nbsp; We maintain high standards of platform and data security
		%li 
			.glyphicon.glyphicon-ok.purplecolor
			&nbsp; We’ll do everything we can to ensure the availability of your content

app/views/visitors/_requirements.html.haml
.box-top

	.lead dokspot is built to work best in the latest desktop and mobile browsers, meaning older browsers might display differently styled, though fully functional, renderings of certain components.

	%p
		Specifically, we support the 
		%strong latest versions 
		of the following browsers and platforms. On Windows,
		%strong we support Internet Explorer 8-11.
		More specific support information is provided below.

	%h3 Browser and Device Support

	.table-responsive.text-center
		%table.table.table-bordered.table-striped
			%thead
				%tr
					%td
					%th Chrome
					%th Firefox
					%th Internet Explorer
					%th Opera
					%th Safari
			%tbody
				%tr
					%th Android
					%td.text-success
						%span.glyphicon.glyphicon-ok
					%td.text-success
						%span.glyphicon.glyphicon-ok
					%td.text-muted{rowspan: 3} N/A
					%td.text-danger
						%span.glyphicon.glyphicon-remove
					%td.text-muted N/A
				%tr
					%th iOS
					%td.text-success
						%span.glyphicon.glyphicon-ok
					%td.text-muted N/A
					%td.text-danger
						%span.glyphicon.glyphicon-remove
					%td.text-success
						%span.glyphicon.glyphicon-ok
				%tr
					%th Mac OS X
					%td.text-success
						%span.glyphicon.glyphicon-ok
					%td.text-success
						%span.glyphicon.glyphicon-ok
					%td.text-success
						%span.glyphicon.glyphicon-ok
					%td.text-success
						%span.glyphicon.glyphicon-ok
				%tr
					%th Windows
					%td.text-success
						%span.glyphicon.glyphicon-ok
					%td.text-success
						%span.glyphicon.glyphicon-ok
					%td.text-success
						%span.glyphicon.glyphicon-ok
					%td.text-success
						%span.glyphicon.glyphicon-ok
					%td.text-danger
						%span.glyphicon.glyphicon-remove

	%h3 Content Support

	%p
		dokspot content is delivered in PDF format. If you don't have a PDF reader installed on your computer, you can download it from
		%a{href: "https://get.adobe.com/reader/"} Adobe

app/views/visitors/_terms.html.haml
%h2 Terms of Service ("Terms")
%p Last updated: September 01, 2015

%p Please read these Terms of Service ("Terms", "Terms of Service") carefully before using the www.dokspot.com website (the "Service") operated by dokspot GmbH ("us", "we", or "our").

%p Your access to and use of the Service is conditioned on your acceptance of and compliance with these Terms. These Terms apply to all visitors, users and others who access or use the Service.

%p By accessing or using the Service you agree to be bound by these Terms. If you disagree with any part of the terms then you may not access the Service.




%h3 Content

%p Our Service allows you to post, link, store, share and otherwise make available certain information, text, graphics, videos, or other material ("Content"). You are responsible for the Content that you post to the Service, including its legality, reliability, and appropriateness.

%p By posting Content to the Service, you grant us the right and license to use, modify, publicly perform, publicly display, reproduce, and distribute such Content on and through the Service. You retain any and all of your rights to any Content you submit, post or display on or through the Service and you are responsible for protecting those rights. You agree that this license includes the right for us to make your Content available to other users of the Service, who may also use your Content subject to these Terms.

%p You represent and warrant that: (i) the Content is yours (you own it) or you have the right to use it and grant us the rights and license as provided in these Terms, and (ii) the posting of your Content on or through the Service does not violate the privacy rights, publicity rights, copyrights, contract rights or any other rights of any person.

%h3 Accounts

%p When you create an account with us, you must provide us information that is accurate, complete, and current at all times. Failure to do so constitutes a breach of the Terms, which may result in immediate termination of your account on our Service.

%p You are responsible for safeguarding the password that you use to access the Service and for any activities or actions under your password, whether your password is with our Service or a third-party service.

%p You agree not to disclose your password to any third party. You must notify us immediately upon becoming aware of any breach of security or unauthorized use of your account.    


%h3 Copyright Policy

%p We respect the intellectual property rights of others. It is our policy to respond to any claim that Content posted on the Service infringes the copyright or other intellectual property infringement ("Infringement") of any person.

%p If you are a copyright owner, or authorized on behalf of one, and you believe that the copyrighted work has been copied in a way that constitutes copyright infringement that is taking place through the Service, you must submit your notice in writing to the attention of "Copyright Infringement" of copyright@dokspot.com and include in your notice a detailed description of the alleged Infringement.

%p You may be held accountable for damages (including costs and attorneys' fees) for misrepresenting that any Content is infringing your copyright.

%h3 Intellectual Property
%p The Service and its original content (excluding Content provided by users), features and functionality are and will remain the exclusive property of dokspot GmbH and its licensors. The Service is protected by copyright, trademark, and other laws of both the Switzerland and foreign countries. Our trademarks and trade dress may not be used in connection with any product or service without the prior written consent of dokspot GmbH.

%h3 Links To Other Web Sites

%p Our Service may contain links to third-party web sites or services that are not owned or controlled by dokspot GmbH.

%p dokspot GmbH has no control over, and assumes no responsibility for, the content, privacy policies, or practices of any third party web sites or services. You further acknowledge and agree that dokspot GmbH shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with use of or reliance on any such content, goods or services available on or through any such web sites or services.

%p We strongly advise you to read the terms and conditions and privacy policies of any third-party web sites or services that you visit.

%h3 Termination

%p We may terminate or suspend your account immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms.

%p Upon termination, your right to use the Service will immediately cease. If you wish to terminate your account, you may simply discontinue using the Service.

%h3 Limitation Of Liability

%p In no event shall dokspot GmbH, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from (i) your access to or use of or inability to access or use the Service; (ii) any conduct or content of any third party on the Service; (iii) any content obtained from the Service; and (iv) unauthorized access, use or alteration of your transmissions or content, whether based on warranty, contract, tort (including negligence) or any other legal theory, whether or not we have been informed of the possibility of such damage, and even if a remedy set forth herein is found to have failed of its essential purpose.

%h3 Disclaimer

%p Your use of the Service is at your sole risk. The Service is provided on an "AS IS" and "AS AVAILABLE" basis. The Service is provided without warranties of any kind, whether express or implied, including, but not limited to, implied warranties of merchantability, fitness for a particular purpose, non-infringement or course of performance.

%p dokspot GmbH its subsidiaries, affiliates, and its licensors do not warrant that a) the Service will function uninterrupted, secure or available at any particular time or location; b) any errors or defects will be corrected; c) the Service is free of viruses or other harmful components; or d) the results of using the Service will meet your requirements.

%h3 Governing Law

%p These Terms shall be governed and construed in accordance with the laws of Switzerland, without regard to its conflict of law provisions.

%p Our failure to enforce any right or provision of these Terms will not be considered a waiver of those rights. If any provision of these Terms is held to be invalid or unenforceable by a court, the remaining provisions of these Terms will remain in effect. These Terms constitute the entire agreement between us regarding our Service, and supersede and replace any prior agreements we might have between us regarding the Service.

%p.lead Changes

%p We reserve the right, at our sole discretion, to modify or replace these Terms at any time. If a revision is material we will try to provide at least 30 days notice prior to any new terms taking effect. What constitutes a material change will be determined at our sole discretion.

%p By continuing to access or use our Service after those revisions become effective, you agree to be bound by the revised terms. If you do not agree to the new terms, please stop using the Service.

%p.lead Contact Us

%p If you have any questions about these Terms, please contact us.

app/views/visitors/_visitor_nav.html.haml
%br
%ul.list-unstyled.visitor-nav{style: 'text-weight: 200'}
	%li.h4 ABOUT
	%li.h5= link_to 'About Us', about_path, class: 'purplecolor'
	%li.h5= link_to 'System Requirements', requirements_path, class: 'purplecolor'
	%br

	%li.h4 POLICIES
	%li.h5= link_to 'Terms of Service', terms_path, class: 'purplecolor'
	%li.h5= link_to 'Customer Promises', promise_path, class: 'purplecolor'
	<!--%li.h5= link_to 'Privacy Policy', privacy_path-->
	%br

	%li.h4 CONTACT
	%li.h5
		%a.purplecolor{ href: "mailto: talk@dokspot.com"} talk@dokspot.com
	%li.h5
		%a.purplecolor{ href: "tel:+12345678987" } +41 79 216 38 28

app/views/visitors/about.html.haml
- title "About"

.container-fluid.purple-bg
  .container
    .row
      .col-xs-12
        %h2.lead ABOUT DOKSPOT

.container
  .row
    .col-sm-8
      = render 'about'
    .col-sm-4.hidden-xs
      = render 'visitor_nav'

app/views/visitors/business.html.haml
- title "Business"

.container-fluid
  .container
    .row
      .col-xs-12
        %h2.lead.purplecolor OUR BUSINESS

= render 'business'

app/views/visitors/demo.html.haml
- title "The Demo"

/ Main jumbotron for a primary marketing message or call to action
.jumbotron.content-header.text-center
  .container
    %h1 DEMO
    %p your customers' experience - take a test drive
.container
  / Example row of columns
  .row
    .text-center.col-sm-3
      =image_tag "28.png", class: "img"
      %h2.lead the dokspot code
      %p.text-justify Each instruction is given a unique dokspot code, supplied with the product.
      %p.text-justify
        In this demo we use:
        %strong DKS16
      %p.text-justify Or scan this QR code (may also be supplied with the product) with your smartphone and jump to step 3.
      %hr.visible-xs-block.visible-sm-block
    .text-center.col-sm-3
      =image_tag "30.png", class: "img", style: "max-width: 200"
      %h3.lead view the product page
      %p.text-justify
        Now that you have a code, head over to
      %p.text-center
        %a{:href => "http://www.dokspot.com", :target => "_blank"} dokspot.com
      %p.text-justify and enter the code.
      %hr.visible-xs-block.visible-sm-block
    .text-center.col-sm-3
      =image_tag "23.png", class: "img"
      %h3.lead select a language
      %p.text-justify View all languages that the instruction has been made available as well as any important messages related to the product.
    .text-center.col-sm-3
      =image_tag "31.png", class: "img"
      %h3.lead view the instruction
      %p.text-justify Congratulation! You are now viewing your first document on the dokspot platform!
      %p.text-justify Simple enough? We think so. Click below to find out more about the service.
  .row{:style => "margin-top: 50px; margin-bottom: 50px"}
    .col-sm-3.text-center.hidden-xs
      %button.btn.btn-default.btn-primary{"data-target" => "#modalDemo1", "data-toggle" => "modal", :type => "button"} More Info
    .col-sm-3.text-center.hidden-xs
      %button.btn.btn-default.btn-primary{"data-target" => "#modalDemo2", "data-toggle" => "modal", :type => "button"} More Info
    .col-sm-3.text-center.hidden-xs
      %button.btn.btn-default.btn-primary{"data-target" => "#modalDemo3", "data-toggle" => "modal", :type => "button"} More Info
    .col-sm-3.text-center
      =link_to "The Service", service_path, class: "btn btn-default btn-success"  
      
/ /container
#modalDemo1.modal.fade.pg-show-modal{"aria-hidden" => "true", :role => "dialog", :tabindex => "-1"}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
        %h4.modal-title the dokspot code
      .modal-body
        .row
          .col-md-6
            =image_tag "29.png", class: "img", width: 270
          .col-md-6
            %p.text-justify Customers receive a unique dokspot code with each product. For added customer convenience device manufacturers may also choose to supply a QR code. Both codes are automatically generated through the dokspot platform for further use by the device manufacturer.
            %p.text-justify Device manufacturers can choose from several dokspot templates for communication of the dokspot code, ranging from labels on consumable products, a permanent label on reusable devices or equipment or a product insert supplied with each product.
#modalDemo2.modal.fade.pg-show-modal{"aria-hidden" => "true", :role => "dialog", :tabindex => "-1"}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
        %h4.modal-title view the product
      .modal-body
        .row
          .col-md-6
            =image_tag "32.png", class: "img", width: 270
          .col-md-6
            %p.text-justify With dokspot your customers get access to language tailored instructions quickly and securely. Our 2-step process is specifically designed for positive customer experience. If you customers want to read instructions they just enter the dokspot code in the dedicated platform or scan the QR code and select their language. 
            %p.text-justify dokspot service is accessible 24/7, thus allowing your customers access to instructions anytime and anywhere even without breaking the product seal.
#modalDemo3.modal.fade.pg-show-modal{"aria-hidden" => "true", :role => "dialog", :tabindex => "-1"}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
        %h4.modal-title select a language
      .modal-body
        .row
          .col-md-6
            =image_tag "33.png", class: "img", width: 270
          .col-md-6
            %p.text-justify Most instructions have a font size of 6 or smaller which is known to lead to slower reading pace and a reduced overall comprehension of the material. In addition customer receive instructions in many languages they don’t need, which is seen as cumbersome and wasteful.
            %p.text-justify dokspot improves your customers’ experience by providing language tailored instructions on a dedicated platform.

app/views/visitors/index.html.haml
- title "Home"

#launch-page
  -#.row
    -#.container.pg-empty-placeholder.lg-container.hidden-xs
    -#.container.pg-empty-placeholder.md-container.visible-xs
  .row
    .col-xs-10.col-sm-6.col-md-4.col-xs-offset-1.col-sm-offset-3.col-md-offset-4
      #search_box
        = simple_form_for :search, url: search_path, method: :post do |f|
          .input-group
            =f.input :query, input_html: { class: 'form-control search-form-input', placeholder: 'Enter Code', autofocus: true }, label: false
            %span.input-group-btn
              %button.btn.search-form-input{style: "background-color: none; width: 82px"}
                =image_tag 'dokspot-circle.png', style: "height: 48px"
      = render 'layouts/messages'
    -#.container.pg-empty-placeholder

app/views/visitors/promise.html.haml
- title "Customer Promises"

.container-fluid.purple-bg
  .container
    .row
      .col-xs-12
        %h2.lead CUSTOMER PROMISES

.container
  .row
    .col-sm-8
      = render 'promise'
    .col-sm-4.hidden-xs
      = render 'visitor_nav'

app/views/visitors/requirements.html.haml
- title "System Requirements"

.container-fluid.purple-bg
  .container
    .row
      .col-xs-12
        %h2.lead SYSTEM REQUIREMENTS

.container
  .row
    .col-sm-8
      = render 'requirements'
    .col-sm-4.hidden-xs
      = render 'visitor_nav'

app/views/visitors/terms.html.haml
- title "Terms of Service"

.container-fluid.purple-bg
  .container
    .row
      .col-xs-12
        %h2.lead TERMS OF SERVICE

.container
  .row
    .col-sm-8
      = render 'terms'
    .col-sm-4.hidden-xs
      = render 'visitor_nav'