config/routes.rb
Rails.application.routes.draw do

  get 'service', to: 'visitors#service'
  get 'about', to: 'visitors#about'
  get 'demo', to: 'visitors#demo'
  get 'terms', to: 'visitors#terms'
  get 'business', to: 'visitors#business'
  get 'promise', to: 'visitors#promise'
  get 'privacy', to: 'visitors#privacy'
  get 'requirements', to: 'visitors#requirements'
  
  get 'qrcode/show'

  devise_for :users, skip: :registrations
  resources :users do
    get :promote
    get :demote
  end

  resources :companies do
    resources :products, except: :index, shallow: true
  end
  
  resources :products, path: '', except: [:index, :new, :create] do
    resources :instructions, shallow: true
    resources :notifications, shallow: true, except: :show
    get :download_qrcode
  end
  
  #resources :instructions, only: [:show, :edit, :destroy]
  #except: [:new, :index]
  
  resources :instructions, except: [:index, :new, :create] do
    resources :documents, except: :show, shallow: true
		resources :orders, shallow: true
    get :primary
  end
  
  resources :documents, except: :show do
    get :download
  end

  root to: 'visitors#index'
  
  post :search, to: "visitors#search"
  
  post "/about"     => "customers#contact"    , :as => :contact
  post "/callback"  => "customers#callback"   , :as => :callback
  get "customers/close/:id"  => "customers#close"   , :as => :close
  
end

app/models/instruction.rb
class Instruction < ActiveRecord::Base
  belongs_to  :product
  belongs_to  :language
  has_many    :documents
  has_many    :orders
  
  accepts_nested_attributes_for :documents
	
	# update for surgical guide, must make db changes.
	enum category: {
		ifu:				    1,
		surgical:       2,
    sterilization:  3
	}
  
  validates :language,     presence: true
  validates :product,      presence: true
  #validates :category,     presence: true
  
  scope :published, -> { where(published: true) }
  
  def primary
    self.documents.where(primary: true).first
  end
  
end

app/controllers/instructions_controller.rb
require 'open-uri'

class InstructionsController < ApplicationController
  before_action :set_instruction, only: [:show, :edit, :update, :destroy]
  before_action :set_product, only: [:new, :create, :index]
  after_action :verify_authorized

  skip_before_filter :authenticate_user!, only: [:show, :primary]

  # GET /instructions/1
  # GET /instructions/1.json
  def show
    authorize @instruction
    @product = @instruction.product
  end

  # GET /instructions/new
  def new
    #@instruction = Instruction.new
    @instruction = @product.instructions.build
    @instruction.documents.build
    authorize @instruction
    @languages = Language.all - @product.languages
  end

  # GET /instructions/1/edit
  def edit
    authorize @instruction
    @languages = Language.all - @instruction.product.languages #+ @instruction.language
    @languages << @instruction.language
  end

  # POST /instructions
  # POST /instructions.json
  def create
    @languages = Language.all - @product.languages

    #@instruction = Instruction.new(instruction_params)
    @instruction = @product.instructions.build(instruction_params)
    authorize @instruction

    respond_to do |format|
      if @instruction.save

        require 'mixpanel-ruby'
        tracker = Mixpanel::Tracker.new(ENV['MIXPANEL_PROJECT_TOKEN'])
        tracker.track(current_user.id, 'Instruction Create', @instruction.attributes)

        format.html { redirect_to @instruction.product, notice: I18n.t('instructions.create.success') }
        format.json { render :show, status: :created, location: @instruction }
      else

        require 'mixpanel-ruby'
        tracker = Mixpanel::Tracker.new(ENV['MIXPANEL_PROJECT_TOKEN'])
        tracker.track(current_user.id, 'Instruction Create Failed', @instruction.attributes)

        format.html { render :new }
        format.json { render json: @instruction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /instructions/1
  # PATCH/PUT /instructions/1.json
  def update
    authorize @instruction
    respond_to do |format|
      if @instruction.update(instruction_params)

        require 'mixpanel-ruby'
        tracker = Mixpanel::Tracker.new(ENV['MIXPANEL_PROJECT_TOKEN'])
        tracker.track(current_user.id, 'Instruction Update', @instruction.attributes)

        format.html { redirect_to @instruction.product, notice: I18n.t('instructions.update.success') }
        format.json { render :show, status: :ok, location: @instruction }
      else

        require 'mixpanel-ruby'
        tracker = Mixpanel::Tracker.new(ENV['MIXPANEL_PROJECT_TOKEN'])
        tracker.track(current_user.id, 'Instruction Update Failed', @instruction.attributes)

        format.html { render :edit }
        format.json { render json: @instruction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /instructions/1
  # DELETE /instructions/1.json
  def destroy
    authorize @instruction
    product = @instruction.product

    require 'mixpanel-ruby'
    tracker = Mixpanel::Tracker.new(ENV['MIXPANEL_PROJECT_TOKEN'])
    tracker.track(current_user.id, 'Instruction Delete', @instruction.attributes)

    @instruction.destroy
    respond_to do |format|
      format.html { redirect_to product, notice: I18n.t('instructions.destroy.success') }
      format.json { head :no_content }
    end
  end

  def primary
    @instruction = Instruction.find(params[:instruction_id])
    @document = @instruction.primary
    authorize @document

    puts @document.file
    #@document.download
    data = open(@document.file.url)
    # send_data data.read, filename: @document.fileName, type: 'application/pdf', disposition: :attachment, stream: true, buffer_size: 4096
    # send_data(data, filename: @document.fileName, type: 'application/pdf', disposition: :inline)
    send_data data.read, filename: @document.fileName, type: 'application/pdf'

    require 'mixpanel-ruby'
    tracker = Mixpanel::Tracker.new(ENV['MIXPANEL_PROJECT_TOKEN'])

    user_id = 0
    user_id = current_user.id if user_signed_in?

    tracker.track(user_id, 'Document Open', {
      product_id: @instruction.product.id,
      product_uuid: @instruction.product.uuid,
      language: @instruction.language.name,
      version: @document.version,
      url: @document.file.url
    })
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_instruction
      @instruction = Instruction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def instruction_params
      params.require(:instruction).permit(:product_id, :language_id, :published, :category, documents_attributes: [:version, :file, :primary])
    end

    def set_product
      @product = Product.friendly.find(params[:product_id])
    end
end

app/helpers/instructions_helper.rb
module InstructionsHelper
end

app/views/instructions/_breadcrumbs.html.haml
.xs-margin-top
  %ol.breadcrumb
  
    - if action_name == 'show'
      - if user_signed_in?
        %li
          = link_to @instruction.product.company.name, @instruction.product.company if policy(@instruction.product.company).show?
    
      %li
        = link_to @instruction.product.name, @instruction.product if policy(@instruction.product).show?
      %li.active
        = link_to @instruction.language.name, @instruction if policy(@instruction).show?
    - elsif action_name == 'new'
      %li
        = link_to @product.company.name, @product.company if policy(@product.company).show?
      %li
        = link_to @product.name, @product if policy(@product).show?
      %li.active
        = link_to t('new.instruction'), new_product_instruction_path(@product) if policy(Instruction.new(product: @product)).new?
    - elsif action_name == 'edit'
      %li
        = link_to @instruction.product.company.name, @instruction.product.company if policy(@instruction.product.company).show?
      %li
        = link_to @instruction.product.name, @instruction.product if policy(@instruction.product).show?
      %li
        = link_to @instruction.language.name, @instruction if policy(@instruction).show?
      %li.active
        = link_to t('keywords.edit'), edit_instruction_path(@instruction) if policy(@instruction).edit?

app/views/instructions/_delete.html.haml
- if policy(instruction).destroy?
  %button.btn.btn-danger.btn-xs{data: {toggle: 'modal', target: "#deleteInstruction#{instruction.id}"}}
    = t('keywords.delete')
  
  .modal.fade{id: "deleteInstruction#{instruction.id}", tabIndex: '-1', role: 'dialog', aria: {labelledby: "deleteInstruction#{instruction.id}", hidden: true}}
    .modal-dialog
      .modal-content
        .modal-header
          %button.close{data: {dismiss: 'modal'}, type: 'button'}
            %span{aria:{hidden:true}} &times;
            %span.sr-only Close
          %h4.modal-title.text-danger.text-center
            = t('keywords.warning')
        .modal-body.text-left
          %p= t('instructions.destroy.warning')
        .modal-footer
          %button.btn.btn-default{data:{dismiss:'modal'}} Close
          = link_to t('keywords.delete'), instruction, method: :delete, class: 'btn btn-danger'

app/views/instructions/_form.html.haml
= simple_form_for [@product, @instruction] do |f|
	= f.error_notification

	.form-inputs  

		.form-group
			-# Moving back to all langs due to categories update. need fix in future. @languages
			= f.association :language, collection: Language.all, input_html: { autofocus: true, class: 'form-control' }, include_blank: false
			
		.form-group  
			= f.input :category, collection: Instruction.categories.map {|k, v| [t(k), k]}, prompt: 'Select Category', input_html: { class: 'form-control'}
      
		- if action_name == 'new' or action_name == 'create'
			= f.simple_fields_for :documents do |d|
				.form-group
					= d.input :version, input_html: { class: 'form-control', placeholder: 'e.g. 1.0' }
				%br
				.form-group
					= d.input :file, as: :file
				%br
				.form-group
					= d.input :primary, as: :hidden, input_html: { value: true }

		.form-group
			= f.check_box :published
			= f.label :published

	.form-actions
		.text-center
			- if action_name == 'new' or action_name == 'create'
				= f.submit "Create Document", class: 'btn btn-success'
			- else
				= f.submit "Update Document", class: 'btn btn-success'

app/views/instructions/_index.html.haml
%br

%table.table.table-hover
  %tr
    %th Language
    -if user_signed_in?
      %th Published
      %th
    %th
    %th
    %th

  - if user_signed_in?
    - product.instructions.where(category: category).each do |instruction|
      %tr
        %td= instruction.language.name
        %td= render partial: "support/published", locals: {object: instruction}

        - if policy(instruction).primary?
          %td
            =link_to instruction_primary_path(instruction), { class: 'btn btn-success btn-xs', target: '_blank' } do
              %span.glyphicon.glyphicon-file{title: 'Open Instruction'}
              = t('instructions.primary')

        - if policy(instruction).show?
          %td
            =link_to instruction_path(instruction), class: 'btn btn-default btn-xs' do
              %span.glyphicon.glyphicon-repeat{title: 'View History'}
              = t('instructions.history')

        - if policy(instruction).edit?
          %td
            =link_to edit_instruction_path(instruction), class: 'btn btn-warning btn-xs' do
              %span.glyphicon.glyphicon-edit{title: 'Edit'}
              = t('keywords.edit')

        %td= render "instructions/delete", instruction: instruction
  - else
    - product.instructions.published.where(category: category).each do |instruction|
      %tr
        %td= instruction.language.local

        - if policy(instruction).primary?
          %td
            =link_to instruction_primary_path(instruction), { class: 'btn btn-success btn-xs', target: '_blank' } do
              %span.glyphicon.glyphicon-file{title: 'Download Instruction'}
              = t('instructions.primary')

        - if policy(instruction).show?
          - if category != ['ifu', 1]
            %td
          - else
            %td
              =link_to instruction_path(instruction), class: 'btn btn-default btn-xs' do
                %span.glyphicon.glyphicon-repeat{title: 'View History'}
                = t('instructions.history')

        - if policy(instruction).order?
          - if category != ['ifu', 1]
            %td
          - else
            %td
              =link_to new_instruction_order_path(instruction), class: 'btn btn-primary btn-xs' do
                %span.glyphicon.glyphicon-envelope{title: 'Order Print'}
                = t('keywords.order')
%br

app/views/instructions/edit.html.haml
= render 'breadcrumbs'

.row.xs-margin-top
  .col-xs-12.col-sm-8.col-md-6.col-lg-4.col-sm-offset-2.col-md-offset-3.col-lg-offset-4
  
    .panel.panel-default

      .panel-heading
        %h1.panel-title Edit instruction
          
      .panel-body
        = render 'form'

app/views/instructions/new.html.haml
= render 'breadcrumbs'

.row.xs-margin-top
  .col-xs-12.col-sm-8.col-md-6.col-lg-4.col-sm-offset-2.col-md-offset-3.col-lg-offset-4
  
    .panel.panel-default

      .panel-heading
        %h1.panel-title New document
          
      .panel-body
        = render 'form'

app/views/instructions/show.html.haml
- title "#{@instruction.product.uuid} - #{@instruction.language.name}"

= render 'breadcrumbs'

.jumbotron
	%h2
		Document History
		%br
		%small= @instruction.category.upcase
		%br
		%small
			= @instruction.product.name
			= "-"
			= @instruction.language.name

= render partial: "documents/index", locals: { instruction: @instruction } if policy(Document.new(instruction: @instruction)).index?