config/routes.rb
Rails.application.routes.draw do

  get 'service', to: 'visitors#service'
  get 'about', to: 'visitors#about'
  get 'demo', to: 'visitors#demo'
  get 'terms', to: 'visitors#terms'
  get 'business', to: 'visitors#business'
  get 'promise', to: 'visitors#promise'
  get 'privacy', to: 'visitors#privacy'
  get 'requirements', to: 'visitors#requirements'
  
  get 'qrcode/show'

  devise_for :users, skip: :registrations
  resources :users do
    get :promote
    get :demote
  end

  resources :companies do
    resources :products, except: :index, shallow: true
  end
  
  resources :products, path: '', except: [:index, :new, :create] do
    resources :instructions, shallow: true
    resources :notifications, shallow: true, except: :show
    get :download_qrcode
  end
  
  #resources :instructions, only: [:show, :edit, :destroy]
  #except: [:new, :index]
  
  resources :instructions, except: [:index, :new, :create] do
    resources :documents, except: :show, shallow: true
		resources :orders, shallow: true
    get :primary
  end
  
  resources :documents, except: :show do
    get :download
  end

  root to: 'visitors#index'
  
  post :search, to: "visitors#search"
  
  post "/about"     => "customers#contact"    , :as => :contact
  post "/callback"  => "customers#callback"   , :as => :callback
  get "customers/close/:id"  => "customers#close"   , :as => :close
  
end

app/models/document.rb
class Document < ActiveRecord::Base
  mount_uploader :file, DocumentUploader
  
  belongs_to :instruction
  
  validates :version, presence: true
  validates :file,    presence: true
  
  scope :primary, -> { where(primary: true) }
  scope :nonprimary, -> { where(primary: false) }
  
  def fileName
    "#{self.instruction.product.name}_#{self.instruction.language.name}_#{self.version}.pdf"
  end
end

app/controllers/documents_controller.rb
require 'open-uri'

class DocumentsController < ApplicationController
  before_action :set_document, only: [:show, :edit, :update, :destroy]
  before_action :set_instruction, except: [:show, :edit, :update, :destroy, :download, :make_primary] #only: [:new, :create, :index]

  skip_before_filter :authenticate_user!, only: :download

  # GET /documents
  # GET /documents.json
  def index
    authorize Document
  end

  # GET /documents/1
  # GET /documents/1.json
  #def show
  #end

  # GET /documents/new
  def new
    @document = @instruction.documents.build
    authorize @document
  end

  # GET /documents/1/edit
  def edit
    authorize @document
  end

  # POST /documents
  # POST /documents.json
  def create
    @document = @instruction.documents.build(document_params)
    authorize @document
    disable_primary if @document.primary
    respond_to do |format|
      if @document.save
        format.html { redirect_to @instruction, notice: t('documents.create.success') }
        format.json { render :show, status: :created, location: @document }
      else
        format.html { render :new }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /documents/1
  # PATCH/PUT /documents/1.json

  def update
    authorize @document
    disable_primary if document_params[:primary]
    respond_to do |format|
      if @document.update(document_params)
        format.html { redirect_to @document.instruction, notice: 'Document was successfully updated.' }
        format.json { render :show, status: :ok, location: @document }
      else
        format.html { render :edit }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    authorize @document
    instruction = @document.instruction
    @document.destroy
    respond_to do |format|
      format.html { redirect_to instruction, notice: t('documents.destroy.success') }
      format.json { head :no_content }
    end
  end

  def download
    @document = Document.find(params[:document_id])
    authorize @document
    #@document.download
    # data = open(@document.file.url)
    # send_data data.read, filename: @document.fileName, type: 'application/pdf', disposition: :attachment, stream: true, buffer_size: 4096

    require 'mixpanel-ruby'
    tracker = Mixpanel::Tracker.new(ENV['MIXPANEL_PROJECT_TOKEN'])

    user_id = 0
    user_id = current_user.id if user_signed_in?

    tracker.track(user_id, 'Document Open', {
      product_id: @document.instruction.product.id,
      product_uuid: @document.instruction.product.uuid,
      language: @document.instruction.language.name,
      version: @document.version,
      url: @document.file.url
    })

    data = open(@document.file.url)
    send_data data.read, filename: @document.fileName, type: 'application/pdf'

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_document
      @document = Document.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def document_params
      params.require(:document).permit(:comment, :file, :version, :primary)
    end

    def set_instruction
      @instruction = Instruction.find(params[:instruction_id])
    end

    def disable_primary
      instruction = @document.instruction
      instruction.documents.each do |document|
        if document != @document
          document.primary = false
          document.save
        end
      end
    end
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_breadcrumbs.html.haml
.xs-margin-top
  %ol.breadcrumb
    
    - if action_name == 'new'
      %li
        = link_to @instruction.product.company.name, @instruction.product.company if policy(@instruction.product.company).show?
      %li
        = link_to @instruction.product.name, @instruction.product if policy(@instruction.product).show?
      %li
        = link_to @instruction.language.name, @instruction if policy(@instruction).show?
      %li.active
        = link_to t('new.document'), new_instruction_document_path(@instruction) if policy(Document.new(instruction: @instruction)).new?

app/views/documents/_form.html.haml
= simple_form_for [@instruction, @document] do |f|
  = f.error_notification

  .form-inputs
    .form-group
      = f.input :version, input_html: { class: 'form-control', placeholder: 'e.g. 1.0', autofocus: true}
    %br
    .form-group
      = f.input :file, as: :file
      %p.help-block
        Upload a file in 
        %strong
          = @instruction.language.name
        for product
        %strong
          = @instruction.product.name
    %br
    .form-group
      = f.check_box :primary
      = f.label :primary

    %br
    .form-actions
      .text-center  
        = f.button :submit, class: 'btn-success'

app/views/documents/_index.html.haml
%br

.text-right
  = link_to t('new.document'), new_instruction_document_path(instruction), class: "btn btn-success btn-xs" if policy(Document.new(instruction: instruction)).new?

%br

%table.table.table-hover
  %tr
    %th Version
    %th
    %th
    %th

  - instruction.documents.primary.each do |document|
    %tr
      %td
        = document.version
      %td= link_to t('documents.download'), document_download_path(document), { class: "download btn btn-primary btn-xs", target: '_blank' } if policy(document).download?
      %td
        %span.glyphicon.glyphicon-star.text-success{data:{toggle:"tooltip",placement:"right"}, title:"Primary"}
      %td

  - instruction.documents.nonprimary.order(created_at: :desc).each do |document|
    %tr
      %td
        = document.version
      %td= link_to t('documents.download'), document_download_path(document), { class: "download btn btn-primary btn-xs", target: '_blank' } if policy(document).download?
      %td= link_to t('keywords.make_primary'), document_path(document, document: {primary: true}), method: :put, class: 'btn btn-warning btn-xs' if policy(document).make_primary?
      %td= link_to t('keywords.delete'), document, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: 'btn btn-danger btn-xs' if policy(document).destroy?

app/views/documents/edit.html.haml
%h1 Editing document

= render 'form'

= link_to 'Show', @document
\|
= link_to 'Back', documents_path

app/views/documents/new.html.haml
= render 'breadcrumbs'

.row.xs-margin-top
  .col-xs-12.col-sm-8.col-md-6.col-lg-4.col-sm-offset-2.col-md-offset-3.col-lg-offset-4
  
    .panel.panel-default

      .panel-heading
        %h1.panel-title New version
          
      .panel-body
        = render 'form'

app/views/documents/show.html.haml
%p#notice= notice

%p
  %b Comment:
  = @document.comment
%p
  %b File:
  = @document.file
%p
  %b Version:
  = @document.version

= link_to 'Edit', edit_document_path(@document)
\|
= link_to 'Back', instruction_documents_path(@document.instruction)