config/routes.rb
Rails.application.routes.draw do

  get 'service', to: 'visitors#service'
  get 'about', to: 'visitors#about'
  get 'demo', to: 'visitors#demo'
  get 'terms', to: 'visitors#terms'
  get 'business', to: 'visitors#business'
  get 'promise', to: 'visitors#promise'
  get 'privacy', to: 'visitors#privacy'
  get 'requirements', to: 'visitors#requirements'
  
  get 'qrcode/show'

  devise_for :users, skip: :registrations
  resources :users do
    get :promote
    get :demote
  end

  resources :companies do
    resources :products, except: :index, shallow: true
  end
  
  resources :products, path: '', except: [:index, :new, :create] do
    resources :instructions, shallow: true
    resources :notifications, shallow: true, except: :show
    get :download_qrcode
  end
  
  #resources :instructions, only: [:show, :edit, :destroy]
  #except: [:new, :index]
  
  resources :instructions, except: [:index, :new, :create] do
    resources :documents, except: :show, shallow: true
		resources :orders, shallow: true
    get :primary
  end
  
  resources :documents, except: :show do
    get :download
  end

  root to: 'visitors#index'
  
  post :search, to: "visitors#search"
  
  post "/about"     => "customers#contact"    , :as => :contact
  post "/callback"  => "customers#callback"   , :as => :callback
  get "customers/close/:id"  => "customers#close"   , :as => :close
  
end

app/models/product.rb
class Product < ActiveRecord::Base
  extend FriendlyId
  friendly_id :uuid

  include Rails.application.routes.url_helpers
  include Uuid

  after_initialize :set_default_published, :if => :new_record?

  scope :published, -> { where(published: true) }

  belongs_to  :company
  has_many    :instructions
  has_many    :notifications
  has_many    :languages, through: :instructions

  has_many    :orders, through: :instructions

  has_one     :customer

  def set_default_published
    self.published ||= false
  end

  validates :name,        presence: true
  validates :company,     presence: true

  validates :name,        uniqueness: true
  validates :uuid,        uniqueness: true

  # Paperclip
  has_attached_file :qrcode_png,
    styles: { medium: "300x300>", thumb: "100x100>" },
    storage: :s3,
    s3_credentials: {
      bucket:             ENV['S3_BUCKET'],
      access_key_id:      ENV['S3_KEY'],
      secret_access_key:  ENV['S3_SECRET']
    }
  has_attached_file :qrcode_svg,
    storage:            :fog,
    fog_directory:      ENV['S3_BUCKET'],
    fog_credentials: {
      aws_access_key_id:      ENV['S3_KEY'],
      aws_secret_access_key:  ENV['S3_SECRET'],
      provider: 'AWS',
      region:             'eu-west-1',
      scheme:             'https'
      # host:               's3-eu-west-1.amazonaws.com',
      # endpoint:           'https://s3-eu-west-1.amazonaws.com',
    }

  validates_attachment_content_type :qrcode_png, content_type: "image/png"
  do_not_validate_attachment_file_type :qrcode_svg

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  include ProductsHelper

  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :set_company, only: [:new, :create]

  skip_before_filter :authenticate_user!, only: :show

  after_action :verify_authorized

  # GET /products/1
  # GET /products/1.json
  def show
    authorize @product
    @customer = Customer.new

    require 'mixpanel-ruby'
    tracker = Mixpanel::Tracker.new(ENV['MIXPANEL_PROJECT_TOKEN'])
    if user_signed_in?
      tracker.track(current_user.id, 'Product View', @product.attributes)
    else
      tracker.track(0, 'Product View', @product.attributes)
    end

    page_title = "dokspot - #{@product.uuid}"
  end

  # GET /products/new
  def new
    @product = @company.products.build
    authorize @product
  end

  # GET /products/1/edit
  def edit
    authorize @product
  end

  # POST /products
  # POST /products.json
  def create
    @product = @company.products.build(product_params)
    authorize @product
    # set the company before saving the product
    set_company

    respond_to do |format|
      if @product.save
        generate_qrcode

        require 'mixpanel-ruby'
        tracker = Mixpanel::Tracker.new(ENV['MIXPANEL_PROJECT_TOKEN'])
        tracker.track(current_user.id, 'Product Create', @product.attributes)

        format.html { redirect_to @product, notice: I18n.t('products.create.success') }
        format.json { render :show, status: :created, location: @product }
      else
        require 'mixpanel-ruby'
        tracker = Mixpanel::Tracker.new(ENV['MIXPANEL_PROJECT_TOKEN'])
        tracker.track(current_user.id, 'Product Failed Create', @product.attributes)

        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    authorize @product
    respond_to do |format|
      if @product.update(product_params)

        require 'mixpanel-ruby'
        tracker = Mixpanel::Tracker.new(ENV['MIXPANEL_PROJECT_TOKEN'])
        tracker.track(current_user.id, 'Product Update', @product.attributes)

        format.html { redirect_to @product, notice: I18n.t('products.update.success') }
        format.json { render :show, status: :ok, location: @product }
      else

        require 'mixpanel-ruby'
        tracker = Mixpanel::Tracker.new(ENV['MIXPANEL_PROJECT_TOKEN'])
        tracker.track(current_user.id, 'Product Update Failed', @product.attributes)

        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    authorize @product
    company = @product.company

    require 'mixpanel-ruby'
    tracker = Mixpanel::Tracker.new(ENV['MIXPANEL_PROJECT_TOKEN'])
    tracker.track(current_user.id, 'Product Delete', @product.attributes)

    @product.destroy
    respond_to do |format|
      format.html { redirect_to company, notice: I18n.t('products.destroy.success') }
      format.json { head :no_content }
    end
  end

  def download_qrcode
    @product = Product.friendly.find(params[:product_id])
    authorize @product
    data = open(@product.qrcode_svg.url)
    send_data data.read, filename: @product.name, type: 'image/svg+xml', disposition: :attachment, stream: true, buffer_size: 4096
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :uuid, :published, :company_id, :user_id)
    end

    def set_company
      @company = Company.friendly.find(params[:company_id])
    end

    def generate_qrcode
      # require 'rqrcode'
      puts "Generating QRCode..."
      url = "#{root_url}#{@product.uuid}"
      #puts "URL is #{url}"

      # size = RQRCode.minimum_qr_size_from_string(url)
      # qrcode = RQRCode::QRCode.new(url, size: size, level: :h)
      qrcode = RQRCode::QRCode.new(url)
      # qrcode = RQRCode::QRCode.new("http://github.com/")
      # puts qrcode
      # png = qrcode.as_png

      # SVG
      # svg = RQRCode::Renderers::SVG::render(qrcode)
      svg = qrcode.as_svg
      file = Tempfile.new(['file','.svg'])
      #puts "TempFile Path: #{file.path}"
      file.write(svg.to_s)
      @product.qrcode_svg = file
      @product.save!
      puts "QR Code: #{@product.qrcode_svg.url}"
    end
end

app/helpers/products_helper.rb
module ProductsHelper

  def set_company
    if @product.company.blank?
      @product.company = current_user.company
    end
  end

end

app/views/products/_breadcrumbs.html.haml
.xs-margin-top
  %ol.breadcrumb
    
    - if action_name == 'show'
      - if user_signed_in?
        %li
          = link_to @product.company.name, @product.company if policy(@product.company).show?
      %li.active
        = link_to @product.name, @product if policy(@product).show?
    - elsif action_name == 'new'
      %li
        = link_to @company.name, @company if policy(@company).show?
      %li.active
        = link_to t('new.product'), new_company_product_path(@company) if policy(Product.new(company: @company)).new?
    - elsif action_name == 'edit'
      %li
        = link_to @product.company.name, @product.company if policy(@product.company).show?
      %li
        = link_to @product.name, @product if policy(@product).show?
      %li.active
        = link_to t('keywords.edit'), edit_product_path(@product) if policy(@product).edit?

app/views/products/_delete.html.haml
.btn-group.btn-group-sm
  - if policy(product).edit?
    = link_to t('keywords.edit'), edit_product_path(product), class: 'btn btn-warning'
  - if policy(product).destroy?
    = link_to t('keywords.delete'), '', class: 'btn btn-danger', data: {toggle: 'modal', target: '#deleteProductModal'}
  
- if policy(product).destroy?
  .modal.fade#deleteProductModal{tabIndex: '-1', role: 'dialog', aria: {labelledby: 'deleteProductModal', hidden: true}}
    .modal-dialog
      .modal-content
        .modal-header
          %button.close{data: {dismiss: 'modal'}, type: 'button'}
            %span{aria:{hidden:true}} &times;
            %span.sr-only Close
          %h4.modal-title.text-danger.text-center
            = t('keywords.warning')
        .modal-body.text-left
          %p= t('products.destroy.warning')
        .modal-footer
          %button.btn.btn-default{data:{dismiss:'modal'}} Close
          = link_to t('keywords.delete'), product, method: :delete, class: 'btn btn-danger'

app/views/products/_form.html.haml
= simple_form_for [@company, @product] do |f|
  = f.error_notification
    
  .form-inputs
    .form-group
      = f.input :name, input_html: { class: 'form-control', autofocus: true }
      
    .form-group
      = f.association :company, input_html: { class: 'form-control' } if current_user.admin?
      
    - if current_user.admin? or current_user.manager?
      = f.check_box :published
      = f.label :published
  
  %br

  .form-actions
    .text-center
      = f.button :submit, class: 'btn-success'

app/views/products/_index.html.haml
%br
.text-right
  = link_to t('new.product'), new_company_product_path(@company), class: 'btn btn-success btn-sm' if policy(Product.new(company: @company)).new?
%br
%table.table.table-hover
  %tr
    %th Name
    %th Dokspot Code
    %th Published
    %th

  - @company.products.each do |product|
    %tr
      %td= product.name
      %td= product.uuid
      %td= render partial: "support/published", locals: {object: product}
      %td= link_to t('keywords.show'), product, class: 'btn btn-primary btn-xs' if policy(product).show?

app/views/products/_resources.html.haml
.xs-margin-top

= image_tag product.qrcode_svg.url, class: 'img-responsive qrcode'
%br
.text-center
  = link_to "download .svg", product_download_qrcode_path(product), class: 'btn btn-primary btn-xs'

app/views/products/edit.html.haml
= render 'breadcrumbs'

.row.xs-margin-top
  .col-xs-12.col-sm-8.col-md-6.col-lg-4.col-sm-offset-2.col-md-offset-3.col-lg-offset-4
  
    .panel.panel-default

      .panel-heading
        %h1.panel-title
          Editing
          = @product.name
          
      .panel-body
        = render 'form'

app/views/products/new.html.haml
= render 'breadcrumbs'

.row.xs-margin-top
  .col-xs-12.col-sm-8.col-md-6.col-lg-4.col-sm-offset-2.col-md-offset-3.col-lg-offset-4
  
    .panel.panel-default

      .panel-heading
        %h1.panel-title New product
          
      .panel-body
        = render 'form'

app/views/products/show.html.haml
- title "#{@product.uuid}"

= render 'breadcrumbs'

- if !user_signed_in?
  = render partial: 'notifications/display', locals: { product: @product }

.row
  .visible-xs-block
    = image_tag @product.company.logo.url, class: 'img-responsive', style: 'max-width: 256px;' if @product.company.logo?
    %br
    %br
  .col-sm-8
    .jumbotron
      = render partial: "delete", locals: {product: @product}
      %h3
        =@product.name
        %br
        %small
          = @product.uuid
          %br
          = render partial: "support/published", locals: {object: @product} if user_signed_in?

      %h4= @product.company.name if !user_signed_in?
  -#.col-xs-2.col-sm-4.pull-right
  .col-sm-4.hidden-xs
    = image_tag @product.company.logo.url, class: 'img-responsive' if @product.company.logo?

%br

.text-right
  = link_to t('new.instruction'), new_product_instruction_path(@product), class: 'btn btn-success btn-sm' if policy(Instruction.new(product: @product)).new?

%br

/ NAV TABS
%ul.nav.nav-tabs{role: 'tablist'}
  - Instruction.categories.each_with_index do |val, index|
    - if @product.instructions.where(category: val).count > 0
      %li{class: ("active" if index == 0)}
        =link_to t("#{val[0]}"), "##{val[0]}", role: 'tab', data: { toggle: 'tab' }
  - if user_signed_in?
    %li
      = link_to t('keywords.notifications'), '#notifications', role: 'tab', data: {toggle: 'tab'}
    %li
      = link_to t('keywords.resources'), '#resources', role: 'tab', data: {toggle: 'tab'}

/ TAB PANES
%div.tab-content
  - Instruction.categories.each_with_index do |val, index|
    %div.tab-pane(id="#{val[0]}"){class: ("active" if index == 0)}
      = render partial: "instructions/index", locals: { product: @product, category: val } if policy(Instruction.new(product: @product)).index?
  - if user_signed_in?
    %div.tab-pane#notifications
      = render partial: "notifications/index",  locals: { product: @product }
    %div.tab-pane#resources
      = render partial: "resources",  locals: { product: @product }

/ Call Back
- if !user_signed_in?
  .text-center
    %button.btn.btn-warning.btn-xs{data: { target: "#modalCallback", toggle: "modal" }, href: "" }
      %span.glyphicon.glyphicon-earphone{title: 'Contact Manufacturer'}
      Contact Manufacturer
    %br
    %br
    %span{style: "font-size: 12px;"}
      To 'Open' Adobe Acrobat Reader is required. Download
      %a{href: "https://get.adobe.com/reader/", target: '_blank' } here
      %span .

/ Call Back Modal

#modalCallback.modal.fade.pg-show-modal{"aria-hidden" => "true", :role => "dialog", :tabindex => "-1"}
  .modal-dialog.modal-md
    .modal-content
      = simple_form_for(@customer, url: url_for(action: 'callback', controller: 'customers'), method: :post) do |f|
        .modal-header
          %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
          %h4.modal-title.text-center Contact Manufacturer
        .modal-body
          #callbackErrorMessage
          = f.error_notification

          .form-inputs
            .form-group
              .row
                .col-xs-12
                  = f.input :full_name, input_html: { class: 'form-control' }
              .row
                .col-sm-6
                  = f.input :country, input_html: { class: 'form-control' }
                .col-sm-6
                  = f.input :telephone, input_html: { class: 'form-control' }
              .row
                .col-sm-6
                  = f.input :email, input_html: { class: 'form-control' }
                .col-sm-6
                  = f.input :email_confirmation, input_html: { class: 'form-control' }
              .row
                .col-xs-12
                  = f.input :notes, as: :text, input_html: {class: 'form-control'}
              = f.hidden_field :product, value: @product.id
              /= f.hidden_field :product_id, value: @product.id

        .modal-footer
          %div#spinner-placeholder.pull-left
          %button.btn.pull-right.btn-success#callbackButton{ type: "submit" } Submit